_target_: neural_fcasa.datamodules.hf_wavact_datamodule.DataModule
train_dataset_path: ${data_dir}/processed_data/hf_datasets/train
val_dataset_path: ${data_dir}/processed_data/hf_datasets/val
batch_size: 2
duration: 10
sr: ${sr}
hop_length: ${hop_length}