_target_: neural_fcasa.datamodules.hdf5_wavact_datamodule.DataModule
train_dataset_path: ${data_dir}/processed_data/hdf5/${dataset_name}-tr.hdf5
val_dataset_path: ${data_dir}/processed_data/hdf5/${dataset_name}-cv.hdf5
batch_size: 2
duration: 10
sr: ${sr}
hop_length: ${hop_length}