defaults:
  - global
  - hydra: default
  - datamodule: default
  - model: default
  - trainer: ddp
  - trainer/callbacks: default
  - trainer/logger: tensorboard
  - override hydra/launcher: submitit_slurm
  - _self_

datamodule:
  batch_size: 16
  keep_in_memory: false

trainer:
  num_nodes: 1
  devices: 4
  accumulate_grad_batches: 2
  max_epochs: 400

hydra:
  launcher:
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    name: neural-fcasa
    partition: audible
    nodes: ${trainer.num_nodes}
    exclude: nodeaudible01
    gpus_per_node: ${trainer.devices}
    cpus_per_task: 16
    tasks_per_node: 2
    mem_gb: 500
    timeout_min: 1440