defaults:
  - global
  - hydra: default
  - datamodule: default
  - model: default
  - trainer: ddp
  - trainer/callbacks: default
  - trainer/logger: tensorboard
  - override hydra/launcher: submitit_slurm
  - _self_

datamodule:
  batch_size: 16
  keep_in_memory: false

trainer:
  num_nodes: 1
  devices: 4
  accumulate_grad_batches: 2
  max_epochs: 400

hydra:
  launcher:
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    name: neural-fcasa
    partition: audible
    nodes: ${trainer.num_nodes}
    exclude: nodeaudible01
    gpus_per_node: ${trainer.devices}
    cpus_per_task: 16
    tasks_per_node: ${trainer.devices}
    mem_gb: 500
    timeout_min: 1440
    setup:
      - source /home/ids/smao-22/phd/neural-fcasa/.venv/bin/activate

ckpt_path: '/home/ids/smao-22/phd/neural-fcasa/recipes/ami/models/neural-fcasa/outputs/beta_prior_m=0.5-lmd=10/2026-02-03_10-18-18/0/checkpoints/last.ckpt'