defaults:
  - global
  - hydra: default
  - datamodule: default
  - model: default
  - trainer: ddp
  - trainer/callbacks: default
  - trainer/logger: tensorboard
  - override hydra/launcher: submitit_slurm
  - _self_

datamodule:
  batch_size: 12

trainer:
  num_nodes: 5
  devices: 2
  accumulate_grad_batches: 1
  max_epochs: 200

hydra:
  launcher:
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    name: neural-fcasa
    partition: A40
    nodes: ${trainer.num_nodes}
    exclude: node[29,35]
    gpus_per_node: ${trainer.devices}
    cpus_per_task: 20
    tasks_per_node: 2
    mem_gb: 110
    timeout_min: 3000