defaults:
  - global
  - hydra: default
  - datamodule: default
  - model: default
  - trainer: ddp
  - trainer/callbacks: default
  - trainer/logger: tensorboard
  - override hydra/launcher: submitit_slurm
  - _self_

datamodule:
  batch_size: 16
  keep_in_memory: false
  num_workers: 8

trainer:
  num_nodes: 1
  devices: 4
  accumulate_grad_batches: 2
  max_epochs: 200

hydra:
  launcher:
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    name: neural-fcasa
    partition: audible
    nodes: ${trainer.num_nodes}
    exclude: nodeaudible01
    gpus_per_node: ${trainer.devices}
    cpus_per_task: 12
    tasks_per_node: ${trainer.devices}
    mem_gb: 500
    timeout_min: 1440
    max_num_timeout: 3
    setup:
      - module load cuda
      - source /home/ids/smao-22/phd/neural-fcasa/.venv/bin/activate
      - export NCCL_IB_DISABLE=1
      - export NCCL_P2P_LEVEL=NVL
      - export NCCL_DEBUG=INFO
      - export NCCL_SOCKET_IFNAME=$(ip route get 8.8.8.8 | awk '{print $5; exit}')

    srun_args: ["--cpu-bind=cores"]
    # additional_parameters: {
    #   "cpu_bind": "cores"
    # }

ckpt_path: ${ckpt_dir}/last.ckpt